"use strict";
var sayHello;(function(){let Cq=2463534242,B$=()=>{let x=Cq;x^=x<<13;x^=x>>>17;x^=x<<5;Cq=x;return x;},F=f=>function(){return f(this);},G=f=>function(p1){return f(this,p1);},M=f=>function(p1,p2){return f(this,p1,p2);},CX=f=>function(p1,p2,p3){return f(this,p1,p2,p3,p3);},S=target=>target.$clinit=()=>{},Dx=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls.$meta&&cls.$meta.item){++arrayDegree;cls=cls.$meta.item;}let clsName="";if(cls.$meta.primitive){clsName=cls.$meta.name;}else {clsName=cls.$meta?cls.$meta.name
||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName+="[]";}return clsName;},E=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0){superclass=P();}return function(){superclass.call(this);};},BM=cls=>Df(cls),P=()=>D,DB=()=>{return {$array:null,classObject:null,$meta:{supertypes:[],superclass:null}};},Br=(name,binaryName)=>{let cls=DB();cls.$meta.primitive=true;cls.$meta.name=name;cls.$meta.binaryName=binaryName;cls.$meta.enum=false;cls.$meta.item=null;cls.$meta.simpleName=null;cls.$meta.declaringClass
=null;cls.$meta.enclosingClass=null;return cls;},BN=Br("char","C"),CG=Br("byte","B"),DJ=Br("int","I");
if(typeof BigInt!=='function'){}else if(typeof BigInt64Array!=='function'){}else {}let Db=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;};
function D1(lo,hi){this.lo=lo|0;this.hi=hi|0;}
if(typeof BigInt!=="function"){}else {}if(typeof BigInt!=='function'){function DZ(lo,hi,sup){this.lo=lo;this.hi=hi;this.sup=sup;}
}else {}let Bs=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (Bf(cls))(data);};
if(typeof BigInt64Array!=='function'){}else {}let T=sz=>new Ds(new Uint16Array(sz)),CS=sz=>new Dk(new Int8Array(sz)),Bf=cls=>{let result=cls.$array;if(result===null){function JavaArray(data){(P()).call(this);this.data=data;}JavaArray.prototype=Object.create((P()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.p
=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (Bf(this.type))(dataCopy);};let name="["+cls.$meta.binaryName;JavaArray.$meta={item:cls,supertypes:[P()],primitive:false,superclass:P(),name:name,binaryName:name,enum:false,simpleName:null,declaringClass:null,enclosingClass:null};JavaArray.classObject=null;JavaArray.$array=null;result=JavaArray;cls.$array
=JavaArray;}return result;},BA,Dl=strings=>{DO();BA=new Array(strings.length);for(let i=0;i<strings.length;++i){BA[i]=Ce(Bg(strings[i]));}},K=index=>BA[index],Cb=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},Bg=str=>str===null?null:C1(str),Bc=str=>str===null?null:str.Q,DO=()=>Q(),Ce;
{Ce=str=>str;}let DR=(obj,cls)=>obj instanceof P()&&!!obj.constructor.$meta&&Bn(obj.constructor,cls),Bn=(from,to)=>{if(from===to){return true;}let map=from.$meta.assignableCache;if(typeof map==='undefined'){map=new Map();from.$meta.assignableCache=map;}let cachedResult=map.get(to);if(typeof cachedResult!=='undefined'){return cachedResult;}if(to.$meta.item!==null){let result=from.$meta.item!==null&&Bn(from.$meta.item,to.$meta.item);map.set(to,result);return result;}let supertypes=from.$meta.supertypes;for(let i
=0;i<supertypes.length;i=i+1|0){if(Bn(supertypes[i],to)){map.set(to,true);return true;}}map.set(to,false);return false;},N=ex=>{throw DP(ex);},CA=Symbol("javaException"),DP=ex=>{let err=ex.$jsException;if(!err){let javaCause=DL(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;err=new L("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[CA]=ex;ex.$jsException=err;C5(err,ex);}return err;},C5
=(err,ex)=>{if(typeof CW==="function"&&err.stack){let stack=CW(err.stack);let javaStack=Bs(Dg(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=Dq(Bg(element.className),Bg(element.methodName),Bg(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){DH(ex,javaStack);}}},L;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");L=function L(message,cause){let self=Reflect.construct(Error,[void 0,cause],L);Object.setPrototypeOf(self,L.prototype);self[defaultMessage]=message;return self;}
;L.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:L},message:{get(){try {let javaException=this[CA];if(typeof javaException==='object'){let javaMessage=CD(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {L=Error;}let CD=t=>Cv(t),DL=t=>Cy(t),Dg=()=>D9,Dq=(className,methodName,fileName,lineNumber)=>
{{return null;}},DH=(e,stack)=>{},Du=outputFunction=>{let buffer="";return msg=>{let index=0;while(true){let next=msg.indexOf('\n',index);if(next<0){break;}outputFunction(buffer+msg.substring(index,next));buffer="";index=next+1;}buffer+=msg.substring(index);};},DK=typeof $rt_putStdoutCustom==="function"?$rt_putStdoutCustom:typeof console==="object"?Du(msg=>console.info(msg)):()=>{},B4=null,CE=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix
=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}B4=packages;},C3=data=>{let packages=B4;let i=0;while(i<data.length){let cls=data[i++];cls.$meta={};let m=cls.$meta;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.superclass=superclass!==0?superclass:null;m.supertypes=data[i++];if(m.superclass){m.supertypes.push(m.superclass);cls.prototype
=Object.create(m.superclass.prototype);}else {cls.prototype={};}let flags=data[i++];m.enum=(flags&8)!==0;m.flags=flags;m.primitive=false;m.item=null;cls.prototype.constructor=cls;cls.classObject=null;m.accessLevel=data[i++];let innerClassInfo=data[i++];if(innerClassInfo===0){m.simpleName=null;m.declaringClass=null;m.enclosingClass=null;}else {let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass
:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit=data[i++];cls.$clinit=clinit!==0?clinit:function(){};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}cls.$array=null;}};
function D(){this.$id$=0;}
let J=a=>{return;},D8=()=>{let a=new D();J(a);return a;},Cs=a=>{let b,c;b=Di(B5(a));c=BS();BC(BC(c,K(0)),b);return Cc(c);},B5=a=>{let b;b=a;if(!b.$id$)b.$id$=B$();return a.$id$;},De=a=>{let b,c,d;if(!DR(a,Ck)){b=a;if(b.constructor.$meta.item===null)N(CF());}c=C_(a);b=c;d=B$();b.$id$=d;return c;};
function R(){let a=this;D.call(a);a.T=null;a.S=null;a.V=0;a.U=0;}
let B_=a=>{a.V=1;a.U=1;a.g();},D0=()=>{let a=new R();B_(a);return a;},Cn=(a,b)=>{a.V=1;a.U=1;a.g();a.T=b;},D7=a=>{let b=new R();Cn(b,a);return b;},DE=a=>{return a;},Cv=a=>{return a.T;},Cy=a=>{return a.S===a?null:a.S;},O=E(R),Bh=a=>{B_(a);},DV=()=>{let a=new O();Bh(a);return a;},Bw=(a,b)=>{Cn(a,b);},D6=a=>{let b=new O();Bw(b,a);return b;},I=E(O),Y=a=>{Bh(a);},DW=()=>{let a=new I();Y(a);return a;},BV=(a,b)=>{Bw(a,b);},D2=a=>{let b=new I();BV(b,a);return b;},Bi=E(I),BH=a=>{Y(a);},Do=()=>{let a=new Bi();BH(a);return a;},DQ
=E(),Dp=(b,c)=>{let d,e,f,g;d=b.data;e=T(c);f=CT(c,d.length);g=0;while(g<f){e.data[g]=d[g];g=g+1|0;}return e;},BY=E(0),BW=E(0),Cx=E(0),V=E(),Bk=a=>{J(a);};
function Bm(){V.call(this);this.ba=null;}
let B6=a=>{BJ(a,32);},Dd=()=>{let a=new Bm();B6(a);return a;},BJ=(a,b)=>{Bk(a);a.ba=CS(b);},DU=a=>{let b=new Bm();BJ(b,a);return b;},C0=E(),BD=null,Dr=()=>{if(BD===null)BD=CM();return BD;};
function Be(){V.call(this);this.bd=null;}
let BG=(a,b)=>{Bk(a);a.bd=b;},DS=a=>{let b=new Be();BG(b,a);return b;},BI=E(0);
function U(){let a=this;Be.call(a);a.bc=0;a.X=null;a.be=null;a.bb=null;}
let Bz=(a,b,c)=>{BG(a,b);a.X=BS();a.be=T(32);a.bc=c;Ba();a.bb=Ch;},DT=(a,b)=>{let c=new U();Bz(c,a,b);return c;},Bu=(a,b)=>{Bz(a,b,0);},D4=a=>{let b=new U();Bu(b,a);return b;},BF=E(U),BR=a=>{Bu(a,Dd());},CJ=(a,b)=>{a.m(b);a.m(K(1));},Ct=E(BF),B0=a=>{BR(a);},CM=()=>{let a=new Ct();B0(a);return a;},DN=(a,b)=>{if(b===null)b=K(2);DK(Bc(b));},DM=E(I),Bb=E(0),Bq=E(),X=E(0),Cf=E(Bq),Dn=null,Bj=()=>{Bj=S(Cf);C9();},Di=b=>{Bj();return Dc(b,4);},DD=b=>{let c,d,e;Bj();if(!b)return 32;c=0;d=b>>>16|0;if(d)c=16;else d=b;e
=d>>>8|0;if(!e)e=d;else c=c|8;d=e>>>4|0;if(!d)d=e;else c=c|4;e=d>>>2|0;if(!e)e=d;else c=c|2;if(e>>>1|0)c=c|1;return (32-c|0)-1|0;},C9=()=>{Dn=BM(DJ);},BZ=E(O),Cd=a=>{Bh(a);},CF=()=>{let a=new BZ();Cd(a);return a;},Dy=E(),C_=b=>{let copy=new b.constructor();for(let field in b){if(b.hasOwnProperty(field)){copy[field]=b[field];}}return copy;},BE=E(),Dm=null,DF=null,BB=()=>{BB=S(BE);CY();},CU=(b,c)=>{BB();if(c>=2&&c<=36&&b>=0&&b<c)return b<10?(48+b|0)&65535:((97+b|0)-10|0)&65535;return 0;},CY=()=>{Dm=BM(BN);DF=
Bs(BE,128);};
function Bl(){let a=this;D.call(a);a.Z=null;a.Y=null;}
let BT=(a,b,c)=>{let d,e,f,g;d=c.data;J(a);Cg(b);e=d.length;f=0;while(f<e){g=d[f];Cg(g);f=f+1|0;}a.Z=b;a.Y=c.p();},Cg=b=>{let c,d;if(b.q())N(Bo(b));if(!Cj(b.s(0)))N(Bo(b));c=1;while(c<b.t()){a:{d=b.s(c);switch(d){case 43:case 45:case 46:case 58:case 95:break;default:if(Cj(d))break a;else N(Bo(b));}}c=c+1|0;}},Cj=b=>{let c;a:{b:{if(!(b>=48&&b<=57)&&!(b>=97&&b<=122)){if(b<65)break b;if(b>90)break b;}c=1;break a;}c=0;}return c;},DI=E(),Dc=(b,c)=>{let d,e,f,g,h,i,j,k;if(!b)return K(3);d=1<<c;e=d-1|0;f=(((32-DD(b)
|0)+c|0)-1|0)/c|0;g=T(f);h=Db(f-1|0,c);i=0;while(h>=0){j=g.data;k=i+1|0;j[i]=CU((b>>>h|0)&e,d);h=h-c|0;i=k;}return CR(g);},Bv=E(0);
function W(){let a=this;D.call(a);a.P=null;a.R=0;}
let Bt=a=>{Bp(a,16);},DY=()=>{let a=new W();Bt(a);return a;},Bp=(a,b)=>{J(a);a.P=T(b);},DX=a=>{let b=new W();Bp(b,a);return b;},B9=(a,b)=>{return a.x(a.R,b);},BP=(a,b,c)=>{let d,e,f;if(b>=0&&b<=a.R){if(c===null)c=K(2);else if(c.q())return a;a.y(a.R+c.t()|0);d=a.R-1|0;while(d>=b){a.P.data[d+c.t()|0]=a.P.data[d];d=d+(-1)|0;}a.R=a.R+c.t()|0;d=0;while(d<c.t()){e=a.P.data;f=b+1|0;e[b]=c.s(d);d=d+1|0;b=f;}return a;}N(BU());},Ci=(a,b,c)=>{return a.z(b,c===null?K(2):c.e());},BX=(a,b)=>{let c;if(a.P.data.length>=b)return;c
=a.P.data.length>=1073741823?2147483647:Ca(b,Ca(a.P.data.length*2|0,5));a.P=Dp(a.P,c);},Cz=a=>{return CH(a.P,0,a.R);},CV=E(),CT=(b,c)=>{if(b<c)c=b;return c;},Ca=(b,c)=>{if(b>c)c=b;return c;},Z=E(I),By=a=>{Y(a);},D5=()=>{let a=new Z();By(a);return a;};
function Cu(){Z.call(this);this.W=null;}
let BO=(a,b)=>{By(a);a.W=b;},Bo=a=>{let b=new Cu();BO(b,a);return b;},H=E(),CL=null,Dt=null,Da=null,Q=()=>{Q=S(H);Dh();},Cp=a=>{Q();J(a);a.Q="";},DC=()=>{let a=new H();Cp(a);return a;},BQ=(a,b)=>{let c;Q();c=b.data;J(a);a.Q=Cb(b.data,0,c.length);},CR=a=>{let b=new H();BQ(b,a);return b;},B8=(a,b)=>{a.Q=b;},C1=a=>{let b=new H();B8(b,a);return b;},Cw=(a,b,c,d)=>{let e;Q();e=b.data;J(a);C4(c,d,e.length);a.Q=Cb(b.data,c,d);},CH=(a,b,c)=>{let d=new H();Cw(d,a,b,c);return d;},DG=(a,b)=>{if(b>=0&&b<a.Q.length)return a.Q.charCodeAt(b);N(BU());},CP
=a=>{return a.Q.length;},CC=a=>{return a.Q.length?0:1;},Dz=a=>{return a;},Dh=()=>{CL=T(0);Dt=DC();Da=CQ();},Ck=E(0),C6=E(),Co=E(Bi),CB=a=>{BH(a);},BU=()=>{let a=new Co();CB(a);return a;},CK=E(),C4=(b,c,d)=>{if(b>=0&&c>=0&&c<=(d-b|0))return b;N(Do());},Cl=E(),Bd=()=>{Bd=S(Cl);C2();},Dj=()=>{Bd();(Dr()).F(K(4));return K(5);},C=()=>{Bd();return Bc(Dj());},C2=()=>{return;},Bx=E(Bl),Ch=null,Ba=()=>{Ba=S(Bx);C8();},C7=a=>{Ba();BT(a,K(6),Bs(H,0));},CN=()=>{let a=new Bx();C7(a);return a;},C8=()=>{Ch=CN();},B2=E(0),BK
=E(0);
function B1(){D.call(this);this.bf=null;}
let DA=(a,b)=>{let c;J(a);a.bf=b;c=a;b.classObject=c;},CI=a=>{let b=new B1();DA(b,a);return b;},Df=b=>{let c;if(b===null)return null;c=b.classObject;if(c===null)c=CI(b);return c;},B7=E(W),Cr=a=>{Bt(a);},BS=()=>{let a=new B7();Cr(a);return a;},BC=(a,b)=>{B9(a,b);return a;},CO=(a,b,c)=>{Ci(a,b,c);return a;},CZ=(a,b,c)=>{BP(a,b,c);return a;},Cc=a=>{return Cz(a);},C$=(a,b)=>{BX(a,b);},Dv=(a,b,c)=>{return a.K(b,c);},Dw=(a,b,c)=>{return a.L(b,c);},Cm=E(0),BL=E(),B3=a=>{J(a);},CQ=()=>{let a=new BL();B3(a);return a;};
CE([]);
C3([D,0,0,[],0,3,0,0,["e",F(Cs),"b",F(B5),"p",F(De)],R,0,D,[],0,3,0,0,["g",F(DE),"M",F(Cv),"N",F(Cy)],O,0,R,[],0,3,0,0,["c",F(Bh),"h",G(Bw)],I,0,O,[],0,3,0,0,["c",F(Y),"h",G(BV)],Bi,0,I,[],0,3,0,0,["c",F(BH)],DQ,0,D,[],0,3,0,0,0,BY,0,D,[],3,3,0,0,0,BW,0,D,[BY],3,3,0,0,0,Cx,0,D,[],3,3,0,0,0,V,0,D,[BW,Cx],1,3,0,0,["c",F(Bk)],Bm,0,V,[],0,3,0,0,["c",F(B6),"j",G(BJ)],C0,0,D,[],4,3,0,0,0,Be,0,V,[],0,3,0,0,["k",G(BG)],BI,0,D,[],3,3,0,0,0,U,0,Be,[BI],0,3,0,0,["l",M(Bz),"k",G(Bu)],BF,0,U,[],1,3,0,0,["c",F(BR),"F",G(CJ)],Ct,
0,BF,[],0,3,0,0,["c",F(B0),"m",G(DN)],DM,0,I,[],0,3,0,0,0,Bb,0,D,[],3,3,0,0,0,Bq,0,D,[Bb],1,3,0,0,0,X,0,D,[],3,3,0,0,0,Cf,0,Bq,[X],0,3,0,Bj,0,BZ,0,O,[],0,3,0,0,["c",F(Cd)],Dy,0,D,[],4,3,0,0,0,BE,0,D,[X],0,3,0,BB,0,Bl,0,D,[X],1,3,0,0,["H",M(BT)],DI,0,D,[],4,3,0,0,0,Bv,0,D,[],3,3,0,0,0,W,0,D,[Bb,Bv],0,0,0,0,["c",F(Bt),"j",G(Bp),"J",G(B9),"z",M(BP),"x",M(Ci),"y",G(BX),"e",F(Cz)],CV,0,D,[],4,3,0,0,0,Z,0,I,[],0,3,0,0,["c",F(By)],Cu,0,Z,[],0,3,0,0,["h",G(BO)],H,0,D,[Bb,X,Bv],0,3,0,Q,["c",F(Cp),"w",G(BQ),"O",G(B8),
"C",CX(Cw),"s",G(DG),"t",F(CP),"q",F(CC),"e",F(Dz)],Ck,0,D,[],3,3,0,0,0,C6,0,D,[],4,0,0,0,0,Co,0,Bi,[],0,3,0,0,["c",F(CB)],CK,0,D,[],4,3,0,0,0,Cl,0,D,[],0,3,0,Bd,0,Bx,0,Bl,[],0,3,0,Ba,0,B2,0,D,[],3,3,0,0,0,BK,0,D,[],3,3,0,0,0,B1,0,D,[BK,B2],0,3,0,0,0,B7,0,W,[BI],0,3,0,0,["c",F(Cr),"d",G(BC),"K",M(CO),"L",M(CZ),"e",F(Cc),"y",G(C$),"x",M(Dv),"z",M(Dw)],Cm,0,D,[],3,3,0,0,0,BL,0,D,[Cm],0,3,0,0,["c",F(B3)]]);
let Ds=Bf(BN),Dk=Bf(CG);
Dl(["<java_object>@","\n","null","0","~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Hello from Java!","Hello from Java!","UTF-8"]);
H.prototype.toString=function(){return Bc(this);};
H.prototype.valueOf=H.prototype.toString;D.prototype.toString=function(){return Bc(Cs(this));};
D.prototype.__teavm_class__=function(){return Dx(this);};
let D3=Symbol('jsoClass');
(()=>{let c;})();
sayHello=C;})();
//# sourceMappingURL=plugin.js.map